### ISSUE TITLE
HTML标签中行内样式无法转换

### ISSUE THREAD

**Issue by TTcom** [kirklin/postcss-px-conversion#1]
### Describe the bug

style标签中的样式无法转换；style="width:100px;"

### Reproduction

style="width:100px;"

### System Info

```Shell
windows10
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/kirklin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/kirklin/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kirklin** [comment]
PostCSS 主要用于处理 CSS 文件，而不是 HTML 中的行内样式。PostCSS 会分析 CSS 文件并对其进行转换、优化或添加前缀等操作。行内样式通常通过HTML标签中的style属性提供，并且PostCSS并不直接处理这些样式。
针对你提到的问题，这个插件并不负责修改HTML标签中的行内样式，而是专注于分析和处理CSS文件中的样式规则。要修改HTML标签中的行内样式，通常需要使用JavaScript来操作。
例如，你可以使用 JavaScript 选取 HTML 元素，并使用 `element.style` 属性来修改其行内样式。
```js
const element = document.getElementById('yourElementId'); // 或者使用其他方式选择你想修改的元素
if (element) {
  element.style.width = '200px';
}
```
当然，如果你想要处理HTML中的行内样式，还有一个可行的方法是使用 `posthtml`，它是一个用于处理HTML的工具，类似于PostCSS但是专注于HTML。

posthtml 允许你创建自定义的插件来转换HTML结构，包括处理行内样式等。你可以编写一个 posthtml 插件来选择和修改HTML标签中的行内样式。
