### ISSUE TITLE
安装 0.1.2 版本 执行 postinstall script 出错，生产环境应该移除

### ISSUE THREAD

**Issue by linhuibin98** [kirklin/postcss-px-conversion#6]
### Describe the bug

{"time":1723710958985,"pid":34232,"level":"error","name":"pnpm","code":"ELIFECYCLE","errno":"ENOENT","syscall":"spawn","file":"sh","pkgid":"postcss-px-conversion@0.1.2","stage":"postinstall","script":"npm run build","pkgname":"postcss-px-conversion","name":"pnpm","err":{"name":"pnpm","message":"postcss-px-conversion@0.1.2 postinstall: `npm run build`\nspawn ENOENT","code":"ELIFECYCLE","stack":"pnpm: postcss-px-conversion@0.1.2 postinstall: `npm run build`\nspawn ENOENT\n    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:82681:22)\n    at ChildProcess.emit (node:events:519:28)\n    at maybeClose (node:internal/child_process:1105:16)\n    at Socket.<anonymous> (node:internal/child_process:457:11)\n    at Socket.emit (node:events:519:28)\n    at Pipe.<anonymous> (node:net:339:12)"}}

### Reproduction

pnpm i postcss-px-conversion

### System Info

```Shell
node.js
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/kirklin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/kirklin/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kirklin** [comment]
Thanks, version 0.1.3 fixes this issue!
