### ISSUE TITLE
两张挨着的图片之间会有 1px 的间距

### ISSUE THREAD

**Issue by qzai666** [kirklin/postcss-px-conversion#8]
### Describe the bug

<div className='flex flex-col'>
        <img
          className='w-full'
          src='https://scdn.joyread.cc/novel_avatar_large_m/6568b1f90eec600dc185d5b606a7c524.jpg'
          alt=''
        />
        <img
          className='w-full'
          src='https://scdn.joyread.cc/novel_avatar_large_m/6568b1f90eec600dc185d5b606a7c524.jpg'
          alt=''
        />
      </div>
      
      图片之间会有1px 的透明横线 

### Reproduction

main

### System Info

```Shell
System:
    OS: macOS 15.0
    CPU: (12) arm64 Apple M3 Pro
    Memory: 68.69 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    pnpm: 8.15.3 - ~/.nvm/versions/node/v16.20.2/bin/pnpm
  Browsers:
    Chrome: 129.0.6668.59
    Safari: 18.0
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/kirklin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/kirklin/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kirklin** [comment]
这个问题很可能是由于浏览器的默认样式引起的，而不是插件的问题。为了帮助确认这一点，我建议您使用一个应用了 `reset CSS` 的简单 Demo 来复现这个问题。如果仍有 1px 的间距，欢迎分享您的代码片段，便于进一步分析。

**Comment by luoriwusheng-xia** [comment]
将图片 变为 display:block   变成块元素， 这是  浏览器的默认样式
